### PR TITLE
Add Farcaster OGs

### PR DESCRIPTION
**Pull request by davidfurlong**

### CODE REVIEW

**Comment by lyoshenka** [comment]
ty @davidfurlong !

**Comment by AbstractsMachine** [comment]
[Banner](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
HackerKang, @philspins, @alvaro-jmp, @greatbsky, @Jerick26, @echoboss, @nntaoli, @jazicorn, @berryjam, @freekatz, @codinggg, @hushino, @adminoid, @Pana, @db80, @ieee0824, @ryandotsmith, @Phunk87, @daiwanwei, @sami2020pro, @alienc0der, @alexlyp, @manhvt081, @BITzy2, @bluejumper, @pcsubirachs, @tzxyz, @pyihe, @todototry, @cfromknecht, @HowardMei, @zhiquan911, @Avanotty27, @charles-m-be, @gianlucamazza, @Va1, @chendehai, @benduncan, @momodezhou, @myneworder, @bradford-hamilton, @mably, @popov-vladimir, @Korede-TA, @iwat, @Yashiroo, @colorgirl4, @Guactoshi, @nimrc, @sighttviewliu

**Comment by AbstractsMachine** [comment]
[Banner](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
iesta, @jrick, @sabey, @facert, @hnq90, @zhou533, @devlzcode, @xylevy, @abanoubha, @frabrunelle, @hcxiong, @hwhe, @kron4eg, @zuoguoji, @jaonoctus, @rbnx, @blastbao, @shockerli, @mendelgusmao, @zoharHao, @imnisen, @stevgarrett, @jeojoe, @UallenQbit, @Unecina, @salisbury-espinosa, @keiko-pixel, @NadBTC, @DavidCai1111, @futoase, @wildownes, @249266, @iinstances, @x13a, @twinsant, @ifvictr, @cocochan55, @liuliuluk, @franquis, @josephawallace, @suapapa, @Godtide, @edwinteo96, @m4h4n, @Ekkohng, @niyuelin1990, @carlbennett, @vt92i, @protez, @BlandyBrains

**Comment by stephaneThannio** [comment]
[Banner](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
JamesLinus, @DINKIN, @diegodelmondes, @curruwilla, @smitherstyle, @samuelPapranec, @liamcrismani, @Samm-Rod, @SamiQu, @Shensd, @chm0815, @Zachinquarantine, @FredMan95, @fforbeck, @Nabeelperson, @davidohayon669, @armandRobled, @lolieosuns, @ian0371, @xfredcox, @Adekunle78, @abelorian, @markapple11, @dec0dOS, @leitaomd, @hypereg, @rafaeldelucena, @dpc525, @rZn, @occhiodipesce, @Azzeccagarbugli, @fitoprincipe, @tscharly, @zmike808, @Ashyur, @sorenstoutner, @KonScanner, @PiEoT, @537, @mpi3d, @altaywtf, @Coding-Enthusiast, @brenohq, @premergencyroom-cs22, @GuipengLiao, @nnnmmm222, @danieletieghi, @luketow, @realFranco, @tactikauan

**Comment by mpi3d** [comment]
This is a phishing attempt. Reporting.

**Pull request merged**
